name: Build and Push Skybot
on:
  push: { branches: [main] } # commits & upstream merges
  workflow_dispatch: # manual button

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # needed for GHCR push
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v5 # official Buildx action :contentReference[oaicite:1]{index=1}
        with:
          context: .
          pull: true # always grab fresh base layers
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/skybot:latest
            ghcr.io/${{ github.repository_owner }}/skybot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
