name: Build, Test & Push Skybot

on:
  push: { branches: [main] }
  pull_request: # PRs run tests but skip push
  workflow_dispatch:

jobs:
  # ──────────────────────────────────────────
  # 1 ▸ Unit-test job  (always runs first)
  # ──────────────────────────────────────────
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5 # same major/minor as Dockerfile
        with: { python-version: "3.11" }

      - name: Install runtime & test deps
        run: |
          pip install -r requirements.txt
          pip install pytest mock

      - name: Run upstream test suite
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/plugins
        run: pytest -q -k "not twitter" #ignoring twitter plugig
        # exits non-zero if any test fails, making build job skip

  # ──────────────────────────────────────────
  # 2 ▸ Build & push job  (runs only if tests pass AND not a PR)
  # ──────────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          pull: true
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/skybot:latest
            ghcr.io/${{ github.repository_owner }}/skybot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
